[meta]
  title = "Text-to-speech Next.js Starter"
  description = "Basic text to speech demo using Deepgram and Next.js"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "TTS"
  language = "JavaScript"
  framework = "Next"

[build]
  command = "npm install"

[config]
  sample = "sample.env.local"
  output = ".env.local"

[post-build]
  message = "Run `npm run dev` to get up and running locally."
